spring.application.name=HealthManagement

# 1. This tells Java the exact internet address of your new TiDB database
# We added ?useSSL=true at the end because TiDB requires a secure connection
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/test?useSSL=true

# 2. This is the username TiDB gave you
spring.datasource.username=q5rFvd3i2b3r8XS.root

# 3. This is the password TiDB gave you
spring.datasource.password=ooeY6lEZEL6YrzXp

# 4. These settings tell Java to automatically create your tables in the new database
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
